### ISSUE TITLE
Map IDs from normalization databases

### ISSUE THREAD

**Issue by jmcejuela** [andreofner/NER_review#6]
* [x] Investigate which mapping direction (UniProt -> EntrezGene, or other way around)
* [x] Check mapping performance (1:1 ? 1:n ? missing ones?)
* [x] Check whether PIR (Protein Information Resource) can be converted to UniProt

---

Solution:

* Use UniProtAPI for UP AC --> EntrezGene Id
* We transform all UniProt ids to EntrezGene ids (both corpora ids & methods ids)

**Comment by andreofner** [comment]
1) EntrezGene -> Uniprot
result from mapping the BioCreativeIII gene mentions (EntrezGene) to Uniprot IDs, using Uniprot mapper: 
- 6046 out of 6359 Entrez Gene Ids mapped to 10224 UniProtKB IDs
- mapping performance: 1:n and missing ones 
- Uniprot has different IDs for same genes/proteins in different species, etc.
- (EntrezGene focused on well known species and genes)
2) Uniprot -> EntrezGene
result from mapping the same 10224 UniProtKB IDs to Entrezgene, using Uniprot mapper: 
- 10,224 identifiers from UniProtKB AC/ID mapped to 6,175 Entrez GeneIDs
- n:1 mapping, but inconsistent (6,175 mapped ~ 6046 original)

**Comment by andreofner** [comment]
PRO/PIR IDs are mapped 1:n to Uniprot. No method normalizes to PRO/PIR directly, so it is not usable.

Result from example mapping, using PIR mapper: http://pir.georgetown.edu/pirwww/search/idmapping.shtml

PRO ID			UniProtKB AC
---------			------------------
PR:000011459		F1QR36,P18280,P20181,P20783,P25433
PR:000004918		P00918,P00920,P07630,P27139
PR:000016877		D4A9G4,F1QJ80,P11344,P14679,P55024
PR:000004920		E1C004,P22748,P48284,Q64444
PR:000001875		F1NDH9,F1QMA9,P48356,P48357,Q62959
PR:000010873		O70624,Q5F0G5,Q99972,Q9R1J4
PR:000009758		P41159,P41160,P50596
PR:000004804		F1P3B2,O35923,P51587,P97929,Q54BU8
PR:000004803		F1N8I5,O54952,P38398,P48754,Q54C05
PR:000013672		B5DF04,P25454,P36601,P37383,P94102,Q06609,Q08297,Q27297,Q557E6,Q5TYR1,Q95Q25
PR:000008457		P68871
PR:000003969		P05187

**Comment by andreofner** [comment]
Mapping the same Identifiers backwards:
- relatively consistent, 1:1 to 1:2 mapping

UniProtKB --> ID/AC	PRO ID
--------------------------
F1QR36		 --> PR:000011459
P18280		 --> PR:000011459
P20181		 --> PR:000011459
P20783		 --> PR:000011459,PR:P20783
P25433		 --> PR:000011459
P00918		 --> PR:000004918,PR:P00918
P00920		 --> PR:000004918
P07630		 --> PR:000004918
P27139		 --> PR:000004918
D4A9G4		 --> PR:000016877
F1QJ80		 --> PR:000016877
P11344		 --> PR:000016877
P14679		 --> PR:000016877,PR:P14679
P55024		 --> PR:000016877
E1C004		 --> PR:000004920
P22748		 --> PR:000004920,PR:P22748
P48284		 --> PR:000004920
Q64444		 --> PR:000004920
F1NDH9		 --> PR:000001875
F1QMA9		 --> PR:000001875
P48356		 --> PR:000001875,PR:P48356
P48357		 --> PR:000001875,PR:P48357
Q62959		 --> PR:000001875
O70624		 --> PR:000010873
Q5F0G5		 --> PR:000010873
Q99972		 --> PR:000010873,PR:Q99972
Q9R1J4		 --> PR:000010873
P41159		 --> PR:000009758,PR:P41159
P41160		 --> PR:000009758
P50596		 --> PR:000009758
F1P3B2		 --> PR:000004804
O35923		 --> PR:000004804
P51587		 --> PR:000004804,PR:P51587
P97929		 --> PR:000004804
Q54BU8		 --> PR:000004804
F1N8I5		 --> PR:000004803
O54952		 --> PR:000004803
P38398		 --> PR:000004803,PR:P38398
P48754		 --> PR:000004803
Q54C05		 --> PR:000004803
B5DF04	 --> 	PR:000013672
P25454		 --> PR:000013672
P36601	 --> 	PR:000013672
P37383		 --> PR:000013672
P94102		 --> PR:000013672
Q06609		 --> PR:000013672,PR:Q06609
Q08297		 --> PR:000013672
Q27297		 --> PR:000013672
Q557E6		 --> PR:000013672
Q5TYR1		 --> PR:000013672
Q95Q25		 --> PR:000013672
P68871		 --> PR:000008457,PR:P68871
P05187		 --> PR:000003969,PR:P05187

**Comment by jmcejuela** [comment]
So what was the corpus with PIR ids ?

**Comment by andreofner** [comment]
The CRAFT corpus, it contains also Entrez Gene mentions.

From the paper:
"Furthermore, most of the sequence mentions that are annotated with multiple Entrez Gene entities due to species ambiguity are more straightforwardly annotated with single taxon-independent PRO concepts. We are more confident of the consistency and utility of the PRO annotations than the Entrez Gene annotations, and we recommend using the former for identification of specific genes and gene products in text."

Complications:
- EntrezGene ID to PRO ID mapping not possible
- PIR Mapping webservice can be used manually only (no API)
- UniProt <-> PRO mapping not 1:1

**Comment by andreofner** [comment]
Overview over normalization databaes so far:

Method Normalization Databases:

1) NEJI				- UniProt
2) GNAT	       			- EntrezGene
3) Moara				- EntrezGene (human), SGD (yeast), MGI (mouse), Flybase (fly)
4) GeneTuKit     		- EntrezGene
5) GNormPlus			- EntrezGene

Corpus normalization databases:

1) BC3				- EntrezGene
2) CRAFT			- EntrezGene, PRO/PIR
3) LocText			- UniProt

**Comment by andreofner** [comment]
From the paper of NEJI:

- converted NEJi and WHATIZIT output (Uniprot) to EntrezGene and PRO:

Results: 95-100% for NEJI, 20-50% for Whatizit
http://www.biomedcentral.com/1471-2105/14/281/table/T1

Paper: see section "CRAFT" 
http://www.biomedcentral.com/1471-2105/14/281

Notes:
- Neji uses Uniprot entries for 21 species while Whatizit uses the entire Uniprot database
- NEJI uses relatively up to date version of Uniprot, Whatizit not

**Comment by jmcejuela** [comment]
I guess for our experiments we will just use CRAFT EntrezGene IDs and forget altogether about PIR/PRO. However, it's good to write the note you found of: 

> We are more confident of the consistency and utility of the PRO annotations ...

Besides, we will be forced to do the EntrezGene <-> UniProt conversions, even if a few errors arise. All these mapping errors will have to be documented too.

**Comment by andreofner** [comment]
1) Regarding the EntrezGene <-> UniProt conversions: My proposal would be to only convert in direction UniProt -> EntrezGene, because it is a n:1 mapping and we would have unique identifiers to compare.

2) I have looked at various conversion tools with an API and have found "biodbnet db2db" (http://biodbnet.abcc.ncifcrf.gov/db/db2db.php) to be the most usable. 
- SOAP API calls
- up to date versions of EntrezGene and Uniprot (http://biodbnet.abcc.ncifcrf.gov/dbInfo/dbVersions.php)
- one has to specify the species for the mapping, which ones should we use?

**Comment by jmcejuela** [comment]
the priblem of uniprot -> entrezgene is precisely that we lose the organism
info, dont we?

In any case, if u have the uniprot id, u know the organism too

**Comment by andreofner** [comment]
Right, I didn't think of that.
I switched from the db2db mapper to the UniProt ID mapper, turns out it does have a usable API.
_______________________________________
Results for converting the LocText corpus to EntrezGene IDs (also in README.md file):

- mapped Uniprot Accession numbers to their corresponding EntrezGene IDs:
	- Total number of successfully mapped IDs:			325
	- Total number of failed mappings:					11
	- Total number of unique UniProt Accession numbers:	325+11 = 336
	- Succesful: 96,73% 
	- Failed: 3.27%

- Detailed list of failed ID mappings (11):
TR-Q92755 | not a valid Uniprot accession number
TR-M4NBC2 | not a valid Uniprot accession number
TR-Q9LMQ2 | not a valid Uniprot accession number
Q3T0J2 
Q93VY4 
Q09187
Q9Y6N3
Q3B891
Q43082 
G9FRT6
E7Q3M8

- mapping statistics WITHOUT invalid UniProt IDs: 
	- Total number of successfully mapped IDs:			325
	- Total number of failed mappings:					8
	- Total number of unique UniProt Accession numbers:	325+8 = 333
	- Succesful: 97,6%
	- Failed: 2.4%

**Comment by jmcejuela** [comment]
Good. I'm gonna check with Tatyana Goldberg, go did the normalizations, about the 3 invalid accession numbers

**Comment by jmcejuela** [comment]
@andreofner Tanya confirmed to me that the "TR-" prefix just means "Trembl", and she wrote it to easily visualize this info. The prefixes should be removed from the corpus.

She also told me that she checked and found 4 of those cases:

TR-Q9LMQ2
TR-M4NBC2
**TR-G9FRT6**
TR-Q92755

**Comment by andreofner** [comment]
Ok, I removed the prefixes.
The 4th case (TR-G9FRT6) is already without prefix (in the pubAnnotation format corpus).

Updated statistics:

Original corpus:
Normalized mentions: 1465 
Not normalized gene mentions: 163 ("obj":"uniprot:uniprot:")

Mapped corpus:
- Successful mapping : 326 (unique IDs) = 97,02%
- Failed mapping: 10 (unique IDs) ~= 2.98%

I have not included the not normalized gene mentions (those that are normalized to "obj":"uniprot:uniprot:") in the final corpus.
163 (~11%) seems to be a quite large number to me, as those would be all false positives for the methods.

**Comment by jmcejuela** [comment]
Do you mean that you didn’t write those normalization ids (obj:
uniprot:uniprot — it actually should be uniprot:) in the corpus written on
github?

I would write them in the corpus, but then for the normalization
performance checks, I would discard those cases.
​
